web:
    volumes:
        - .:/app
    build: .
    command: node index.js
    ports:
        - "3900:3900"
    links:
        - db
    environment:
        MONGO_URI: mongodb://db:27017/myapp
        MONGO_DATABASE: myapp
        MONGO_USER: myapp
        MONGO_PASSWORD: mysecurepass
        MONGO_HOST: db
        depends_on:
            - db

db:
    volumes:
        - .:/app
    image: mongo
    ports:
        - "27017:27017"
    environment:
        MONGO_DATABASE: myapp
        MONGO_USER: myapp
        MONGO_PASSWORD: mysecurepass
