web:
    build: .
    command: node index.js
    ports:
        - "3900:3900"
    links:
        - db
    environment:
        MONGO_DATABASE: vidly
        MONGO_USER: vidly
        MONGO_PASSWORD: mysecurepass
        MONGO_HOST: db

db:
    image: mongo
    ports:
        - "27017:27017"
    environment:
        MONGO_DATABASE: vidly
        MONGO_USER: vidly
        MONGO_PASSWORD: mysecurepass
